config/routes.rb
require 'bowtie'

Cms::Application.routes.draw do
	namespace :structure do
		resources :content_types
		resources :pages
		resources :contents
	end
	resources :posts
  match '/', :controller => :posts, :action => :index
  BOWTIE_AUTH = {:user => 'admin', :pass => '12345'}
  mount Bowtie::Admin, :at => '/admin'
end

app/models/structure/content_type.rb
class Structure::ContentType
  include MongoMapper::Document
  after_save :write_to_file, :update_children
  after_destroy :remove_file, :update_children, :update_parents

  key :name, String

  # Embedded Keys
  many :relationships, :class_name => 'Structure::Relationship'
  many :fields, :class_name => 'Structure::Field'
  many :pages, :class_name => 'Structure::Page'

  def from
    Structure::ContentType.where('relationships.to_id' => self._id).all
  end

  # Necessary?
  def pages
    Structure::Page.where('content_type_id' => self._id).all
  end

  def self.contents
    contents = []
    all.each do |content_type|
      obj = Object.const_get(content_type.name.capitalize)
      contents.push({
        :name => content_type.name.pluralize,
        :id => content_type.id,
        :has_page => Structure::Page.where(:content_type_id => content_type.id).all.count > 0,
        :contents => obj.all
        })
    end
    contents
  end

  def update_embedded_documents(params)
    if params[:fields] == nil
      self.fields = []
      changed = true
    end
    if params[:relationships] == nil
      self.relationships = []
      changed = true
    end
    if changed
      self.save
    end
    return true
  end

  def write_to_file
    # name standardized
    name = self.name.singularize.tr(' ','_')
    model_name = name.camelize
    filename = File.join('app', 'models', (name.underscore + '.rb'))
    File.open(filename, 'w+') do |f|
      # Class declaration
      f << "class #{model_name}
  include MongoMapper::Document
  many :pages, :class_name => Structure::Page, :polymorphic => true\n"
      # Fields
      self.fields.each do |field|
        if (Structure::Field.get_type_options[field.type] == 'Timestamp')
          f << "\ttimestamps!\n"
        else
          f << "\tkey :" + field.title.singularize.tr(' ','_').underscore + ", String\n"
        end
      end
      # Children Relationships
      self.relationships.each do |relationship|
       f << "\tmany :" + relationship.to.name.pluralize.tr(' ','_').underscore + "\n"
      end
      # Parent Relationships
      self.from.each do |content_type|
       f << "\tbelongs_to :" + content_type.name.singularize.tr(' ','_').underscore + "\n"
      end
      f << "end"
    end
  end

  private
  def remove_file
    name = self.name.singularize.tr(' ','_')
    filename = File.join('app', 'models', (name.underscore + '.rb'))
    File.delete(filename)
  end

  private
  def update_children
    self.relationships.each do |relationship|
      relationship.to.write_to_file
    end
  end

  private
  def update_parents
    self.from.each do |content_type|
      # remove obsolete relationships
      content_type.relationships.each do |relationship|
        if relationship.to_id == self._id
          content_type.pull(:relationships => {:to_id => self._id})
        end
      end
      # rewrite model file
      content_type.reload
      content_type.write_to_file
    end
  end
end

app/models/structure/field.rb
class Structure::Field
  include MongoMapper::EmbeddedDocument

  key :title, String
  key :type, Integer

  def self.get_type_options
	['Single line text', 'Multi line text', 'Timestamp']
	#[["Integer", 0], ["Single line text", 1], ["Multi line text", 2]]
  end
end

app/models/structure/page.rb
class Structure::Page
  include MongoMapper::Document
  after_save :unique_homepage, :write_routes, :write_controller_file
  #before_destroy :delete_controller_file
  after_destroy :write_routes, :unique_homepage

  key :name, String
  key :is_homepage, Integer
  belongs_to :content_type, :class_name => "Structure::ContentType"
  belongs_to :content, :polymorphic => true

  private
  def write_routes
  	filename = File.join("config", "routes.rb")
  	File.open(filename, "w+") do |f|
  		f << "Cms::Application.routes.draw do\n"
  		# Structure Routes
  		f << "	namespace :structure do\n"
  		f << "		resources :content_types\n"
  		f << "		resources :pages\n"
  		f << "		resources :contents\n"
  		f << "	end\n"
  		# Content Routes
  		Structure::Page.all.each do |page|
  			f << "	resources :" + page.name.downcase.pluralize + "\n"
  		end
      # Set homepage
      f << "  match '/', :controller => :" + Structure::Page.where(:is_homepage => 1).sort(:updated_at.desc).first.name.downcase.pluralize + ", :action => :index\n"
  		f << "end"
  	end
  end

  private
  def write_controller_file
  	modelname = self.content_type.name.singularize.tr(' ','_').camelize
  	variablename = self.content_type.name.downcase
  	filename = File.join("app", "controllers", self.name.downcase.pluralize + "_controller.rb")
  	File.open(filename, "w+") do |f|
  		f <<
"class #{self.name.pluralize.camelize}Controller < ApplicationController
	def index
		@#{variablename.pluralize} = #{modelname}.all
		respond_to do |format|
			format.html { render json: @#{variablename.pluralize} }
		end
	end

	def show
		@#{variablename.singularize} = #{modelname}.find(params[:id])
		respond_to do |format|
			format.html { render json: @#{variablename.singularize} }
		end
	end
end"
  	end
  end

  private
  def unique_homepage
    with_homepage_set = Structure::Page.where(:is_homepage => 1).sort(:updated_at.desc).all
    # no page with homepage
    if with_homepage_set.size == 0
      page = Structure::Page.sort(:updated_at.desc).first
      page.is_homepage = 1
      page.save
    # set to first
    elsif with_homepage_set.size > 1
      # unset all
      with_homepage_set.each do |page|
        p = page
        p.is_homepage = 0
        p.save
      end
      # set first to homepage
      page = with_homepage_set.first
      page.is_homepage = 1
      page.save
    end
  end
end

app/models/structure/relationship.rb
class Structure::Relationship
  include MongoMapper::EmbeddedDocument

  key :type, Integer
  belongs_to :to, :class_name => 'Structure::ContentType', :typecast => 'ObjectId'

  def self.get_type_options
	#[["has many", 0], ["has one", 1]]
	['has_many']
  end
end

app/controllers/structure/content_types_controller.rb
class Structure::ContentTypesController < ApplicationController
  # GET /content_types
  # GET /content_types.json
  def index
    @content_types = Structure::ContentType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @content_types }
    end
  end

  # GET /content_types/1
  # GET /content_types/1.json
  def show
    @content_type = Structure::ContentType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @content_type, :include => :relationships }
    end
  end

  # GET /content_types/new
  # GET /content_types/new.json
  def new
    @content_type = Structure::ContentType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @content_type }
    end
  end

  # GET /content_types/1/edit
  def edit
    @content_type = Structure::ContentType.find(params[:id])
  end

  # POST /content_types
  # POST /content_types.json
  def create
    @content_type = Structure::ContentType.new(params[:structure_content_type])

    respond_to do |format|
      if @content_type.save
        format.html { redirect_to @content_type, notice: 'Content type was successfully created.' }
        format.json { render json: @content_type, status: :created, location: @content_type }
      else
        format.html { render action: "new" }
        format.json { render json: @content_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /content_types/1
  # PUT /content_types/1.json
  def update
    @content_type = Structure::ContentType.find(params[:id])

    respond_to do |format|
      if @content_type.update_embedded_documents(params[:structure_content_type]) && @content_type.update_attributes(params[:structure_content_type])
        format.html { redirect_to @content_type, notice: 'Content type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @content_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_types/1
  # DELETE /content_types/1.json
  def destroy
    @content_type = Structure::ContentType.find(params[:id])
    @content_type.destroy

    respond_to do |format|
      format.html { redirect_to structure_content_types_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/structure/contents_controller.rb
class Structure::ContentsController < ApplicationController
  # GET /structure/contents
  # GET /structure/contents.json
  def index
    @contents = Structure::ContentType.contents

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contents }
    end
  end

  # GET /structure/contents/1
  # GET /structure/contents/1.json
  def show
    @structure_content = Structure::Content.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @structure_content }
    end
  end

  # GET /structure/contents/new
  # GET /structure/contents/new.json
  def new
    @structure_content = Structure::Content.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @structure_content }
    end
  end

  # GET /structure/contents/1/edit
  def edit
    @structure_content = Structure::Content.find(params[:id])
  end

  # POST /structure/contents
  # POST /structure/contents.json
  def create
    @structure_content = Structure::Content.new(params[:structure_content])

    respond_to do |format|
      if @structure_content.save
        format.html { redirect_to @structure_content, notice: 'Content was successfully created.' }
        format.json { render json: @structure_content, status: :created, location: @structure_content }
      else
        format.html { render action: "new" }
        format.json { render json: @structure_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /structure/contents/1
  # PUT /structure/contents/1.json
  def update
    @structure_content = Structure::Content.find(params[:id])

    respond_to do |format|
      if @structure_content.update_attributes(params[:structure_content])
        format.html { redirect_to @structure_content, notice: 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @structure_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /structure/contents/1
  # DELETE /structure/contents/1.json
  def destroy
    @structure_content = Structure::Content.find(params[:id])
    @structure_content.destroy

    respond_to do |format|
      format.html { redirect_to structure_contents_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/structure/pages_controller.rb
class Structure::PagesController < ApplicationController
  # GET /structure/pages
  # GET /structure/pages.json
  def index
    @structure_pages = Structure::Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @structure_pages }
    end
  end

  # GET /structure/pages/1
  # GET /structure/pages/1.json
  def show
    @structure_page = Structure::Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @structure_page }
    end
  end

  # GET /structure/pages/new
  # GET /structure/pages/new.json
  def new
    @structure_page = Structure::Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @structure_page }
    end
  end

  # GET /structure/pages/1/edit
  def edit
    @structure_page = Structure::Page.find(params[:id])
  end

  # POST /structure/pages
  # POST /structure/pages.json
  def create
    @structure_page = Structure::Page.new(params[:structure_page])

    respond_to do |format|
      if @structure_page.save
        format.html { redirect_to @structure_page, notice: 'Page was successfully created.' }
        format.json { render json: @structure_page, status: :created, location: @structure_page }
      else
        format.html { render action: "new" }
        format.json { render json: @structure_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /structure/pages/1
  # PUT /structure/pages/1.json
  def update
    @structure_page = Structure::Page.find(params[:id])

    respond_to do |format|
      if @structure_page.update_attributes(params[:structure_page])
        format.html { redirect_to @structure_page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @structure_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /structure/pages/1
  # DELETE /structure/pages/1.json
  def destroy
    @structure_page = Structure::Page.find(params[:id])
    @structure_page.destroy

    respond_to do |format|
      format.html { redirect_to structure_pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/content_types_helper.rb
module ContentTypesHelper
	def add_field_link(title, f)
    	# TODO: Fix embedded js
    	link_to_function(title, '$(\'#fields\').append(\'' + escape_javascript(render(:partial => 'field', :locals => {:f => f, :field => Structure::Field.new})) +  '\')')
  	end

  	def add_relationship_link(title, f)
    	# TODO: DRY
    	link_to_function(title, '$(\'#relationships\').append(\'' + escape_javascript(render(:partial => 'relationship', :locals => {:f => f, :relationship => Structure::Relationship.new})) +  '\')')
  	end
end

app/helpers/structure/contents_helper.rb
module Structure::ContentsHelper
end

app/helpers/structure/pages_helper.rb
module Structure::PagesHelper
end

app/views/structure/content_types/_field.html.erb
<div class="field">
 	<%= f.fields_for :fields, field, :index => nil do |f_nested| %>
    	<%= f_nested.label :title %>
    	<%= f_nested.text_field :title %>
    	<%= f_nested.label :type %>
    	<%= f_nested.select(:type, Structure::Field.get_type_options.collect {|f| [f, Structure::Field.get_type_options.index(f)]}) %>
    	<!-- TODO: Fix embedded JS -->
    	<%= link_to_function "(remove)", "$(this).parent().remove()" %>
	<% end %>
</div>

app/views/structure/content_types/_form.html.erb
<%= form_for @content_type, :url => structure_content_type_path(@content_type) do |f| %>
  <% if @content_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content_type.errors.count, "error") %> prohibited this content_type from being saved:</h2>

      <ul>
      <% @content_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %><br />
  <%= f.text_field :name %><br /><br />

  Fields:
  <div id="fields">
    <%= add_field_link("(add field)", f) %>
    <%= render :partial => 'field', :collection => @content_type.fields, :locals => {:f => f} %>
  </div><br />

  Relationships:
  <div id="relationships">
    <%= add_relationship_link("(add relationship)", f) %>
    <%= render :partial => 'relationship', :collection => @content_type.relationships, :locals => {:f => f} %>
  </div><br />


  <div class="actions">
    <%= f.submit %>
  </div><br />
<% end %>

app/views/structure/content_types/_relationship.html.erb
<div class="relationship">
 	<%= f.fields_for :relationships, relationship, :index => nil do |f_nested| %>
    	<%= f_nested.select(:type, Structure::Relationship.get_type_options.collect {|f| [f, Structure::Relationship.get_type_options.index(f)]}) %>
    	<%= f_nested.select(:to_id, Structure::ContentType.all.collect {|c| [c.name, c._id]}) %>
    	<!-- TODO: Fix embedded JS -->
    	<%= link_to_function "(remove)", "$(this).parent().remove()" %>
	<% end %>
</div>

app/views/structure/content_types/edit.html.erb
<h1>Editing content_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @content_type %> |
<%= link_to 'Back', structure_content_types_path %>

app/views/structure/content_types/index.html.erb
<h1>Listing content_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @content_types.each do |content_type| %>
  <tr>
    <td><%= content_type.name %></td>
    <td><%= link_to 'Show', content_type %></td>
    <td><%= link_to 'Edit', edit_structure_content_type_path(content_type) %></td>
    <td><%= link_to 'Destroy', content_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Content type', new_structure_content_type_path %>

app/views/structure/content_types/new.html.erb
<h1>New content_type</h1>

<%= render 'form' %>

<%= link_to 'Back', structure_content_types_path %>

app/views/structure/content_types/show.html.erb
<p id="notice"><%= notice %></p>

<h1>ContentType: <%= @content_type.name %></h1>

<h2>Fields</h2>
<ul><% @content_type.fields.each do |field| %>
	<li><%= field.title %> : <%= Structure::Field.get_type_options[field.type] %></li>
<% end %></ul>

<h2>Relationships</h2>
<ul><% @content_type.relationships.each do |relationship| %>
	<li><%= Structure::Relationship.get_type_options[relationship.type] %> <%= relationship.to.name %></li>
<% end %></ul>

<%= link_to 'Edit', edit_structure_content_type_path(@content_type) %> |
<%= link_to 'Back', structure_content_types_path %>